model_name: 'h2s-test'
dataset_type: 'yasl'
dataset_dir: '/home/kara-nlp/Documents/Repositories/Thesis/SLT/Datasets/How2Sign/Mediapipe'
output_dir: './results'
seed: 42
annotation_file: '/home/kara-nlp/Documents/Repositories/Thesis/SLT/Datasets/YASL/'
metadata_file: '/home/kara-nlp/Documents/Repositories/Thesis/SLT/Datasets/YASL/keypoints/'
skip_frames: False
max_token_length: 128
max_sequence_length: 250
transform: 'yasl'
modality: 'pose'
embedding_dim: 255
model_id: 't5-small'
max_training_steps: 10
save_steps: 10
eval_steps: 2
per_device_train_batch_size: 16
per_device_eval_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 0.001
weight_decay: 0.0
fp16: False
push_to_hub: False
logging_steps: 1
pose_dim: 255
num_beams: 5
length_penalty: 0.6
early_stopping: False
no_repeat_ngram_size: 0
dev: True
project_name: 'h2s-t5'
max_val_samples: 6
is_normalized: False